In [6]:
from datetime import datetime

In [7]:
지금 = datetime.now()
지금

datetime.datetime(2016, 12, 16, 15, 1, 6, 632761)

In [8]:
지금.isoformat()

'2016-12-16T15:01:06.632761'

In [9]:
'{}년 {}월 {}일 {}시 {}분 {}초'.format(
            지금.year, 지금.month, 지금.day, 지금.hour, 지금.minute, 지금.second
)

'2016년 12월 16일 15시 1분 6초'

요일

0~6: 월~일

In [10]:
지금.weekday()

4

In [11]:
list('월화수목금토일')[지금.weekday()]

'금'

In [12]:
def 요일추출(날짜시간):
    return list('월화수목금토일')[날짜시간.weekday()]

In [13]:
의문의날짜= '10-01-20'

In [14]:
국제표준 = '%y-%m-%d'
datetime.strptime(의문의날짜, 국제표준)

datetime.datetime(2010, 1, 20, 0, 0)

주어진문자열을 datetime 객체로 생성

* yyyy: %Y
* mm: %m
* dd: %d

In [15]:
좋은날 = '2016년 12월 16일'

In [16]:
date = datetime.strptime(좋은날, '%Y년 %m월 %d일')

In [17]:
date

datetime.datetime(2016, 12, 16, 0, 0)

Time-series. 시간의 흐름에 따라 기록된 자료

In [18]:
import pandas as pd

In [19]:
식당 = pd.read_excel('data/food_order.xlsx')

In [20]:
식당.date[:5]

0   2013-08-06
1   2013-08-06
2   2013-08-06
3   2013-08-06
4   2013-08-06
Name: date, dtype: datetime64[ns]

In [21]:
식당.date[0]

Timestamp('2013-08-06 00:00:00')

In [22]:
날짜 = 식당.date.map(lambda 날짜: '{0.year}년 {0.month}월 {0.day}일'.format(날짜))

In [23]:
날짜[:3]

0    2013년 8월 6일
1    2013년 8월 6일
2    2013년 8월 6일
Name: date, dtype: object

In [24]:
pd.to_datetime(날짜, format='%Y년 %m월 %d일')[:3]

0   2013-08-06
1   2013-08-06
2   2013-08-06
Name: date, dtype: datetime64[ns]

Timestamp = datetime + 알파

In [25]:
어느날 = '2015-10-21'

In [26]:
datetime.strptime(어느날, '%Y-%m-%d')

datetime.datetime(2015, 10, 21, 0, 0)

In [27]:
ts = pd.Timestamp(어느날)
ts

Timestamp('2015-10-21 00:00:00')

In [28]:
ts.year

2015

In [29]:
식당 = 식당.set_index('date')

In [30]:
식당.ix['2013-08-06']

,dine_type,corner,menu,is_sold_out,use_count,pred_count,additional,good,ok,bad,diff_use_pred,year,month,day,wday
date,,,,,,,,,,,,,,,
2013-08-06,dinner,grill & fry,훈제연어벤또(200개),F,213,0,0,0,0,0,-213,2013,8,6,1
2013-08-06,dinner,rice & soup 1,뚝배기 우거지 갈비탕,F,261,0,0,0,0,0,-261,2013,8,6,1
2013-08-06,lunch,noodle bar,판모밀정식,F,267,0,0,0,0,0,-267,2013,8,6,1
2013-08-06,breakfast,rice & soup 1,설렁탕정식,F,1,0,0,0,0,0,-1,2013,8,6,1
2013-08-06,lunch,rice & soup 1,A. 부대찌개정식,F,376,0,0,0,0,0,-376,2013,8,6,1

In [31]:
식당.ix['2013-08']

,dine_type,corner,menu,is_sold_out,use_count,pred_count,additional,good,ok,bad,diff_use_pred,year,month,day,wday
date,,,,,,,,,,,,,,,
2013-08-06,dinner,grill & fry,훈제연어벤또(200개),F,213,0,0,0,0,0,-213,2013,8,6,1
2013-08-06,dinner,rice & soup 1,뚝배기 우거지 갈비탕,F,261,0,0,0,0,0,-261,2013,8,6,1
2013-08-06,lunch,noodle bar,판모밀정식,F,267,0,0,0,0,0,-267,2013,8,6,1
2013-08-06,breakfast,rice & soup 1,설렁탕정식,F,1,0,0,0,0,0,-1,2013,8,6,1
2013-08-06,lunch,rice & soup 1,A. 부대찌개정식,F,376,0,0,0,0,0,-376,2013,8,6,1
2013-08-12,dinner,noodle bar,차슈라멘,F,179,0,0,0,0,0,-179,2013,8,12,0
2013-08-12,breakfast,rice & soup 1,뚝배기순대국,F,26,0,0,0,0,0,-26,2013,8,12,0
2013-08-12,lunch,rice & soup 1,A:누룽지장각백숙,F,504,0,0,0,0,0,-504,2013,8,12,0
2013-08-12,lunch,noodle bar,유니자장면,F,167,0,0,0,0,0,-167,2013,8,12,0
2013-08-12,dinner,rice & soup 1,김치날치알밥,F,216,0,0,0,0,0,-216,2013,8,12,0
2013-08-12,dinner,grill & fry,그릴드함박정식,F,336,0,0,0,0,0,-336,2013,8,12,0
2013-08-12,lunch,grill & fry,가츠엔정식,F,359,0,0,0,0,0,-359,2013,8,12,0
2013-08-13,lunch,rice & soup 1,A: 누룽지장각백숙,F,532,0,0,0,0,0,-532,2013,8,13,1
2013-08-13,lunch,grill & fry,닭날개벤또,F,234,0,0,0,0,0,-234,2013,8,13,1
2013-08-13,dinner,rice & soup 1,분차덮밥,F,457,0,0,0,0,0,-457,2013,8,13,1
2013-08-13,dinner,noodle bar,열무물냉면,F,136,0,0,0,0,0,-136,2013,8,13,1
2013-08-13,dinner,burger&pizza,오곡버거,F,115,0,0,0,0,0,-115,2013,8,13,1
2013-08-13,breakfast,rice & soup 1,사골우거지탕,F,26,0,0,0,0,0,-26,2013,8,13,1
2013-08-13,lunch,noodle bar,유니자장면(밥),F,214,0,0,0,0,0,-214,2013,8,13,1
2013-08-14,lunch,grill & fry,닭날개벤또,F,135,0,0,0,0,0,-135,2013,8,14,2
2013-08-14,breakfast,rice & soup 1,다슬기해장국,F,27,0,0,0,0,0,-27,2013,8,14,2
2013-08-14,dinner,grill & fry,치킨데리야끼스테이크,F,229,0,0,0,0,0,-229,2013,8,14,2
2013-08-14,lunch,rice & soup 1,A: 쇠고기영양탕,F,567,0,0,0,0,0,-567,2013,8,14,2
2013-08-14,lunch,noodle bar,가평잣국수,F,98,0,0,0,0,0,-98,2013,8,14,2
2013-08-14,dinner,rice & soup 1,훈제오리&부추생채,F,280,0,0,0,0,0,-280,2013,8,14,2
2013-08-14,dinner,after school,라면세트,F,114,0,0,0,0,0,-114,2013,8,14,2
2013-08-19,lunch,grill & fry,카레라이스&단각구이,F,314,0,0,0,0,0,-314,2013,8,19,0
2013-08-19,dinner,rice & soup 1,삼겹살김치찜,F,441,0,0,0,0,0,-441,2013,8,19,0
2013-08-19,lunch,after school,라면+롤밥 &고급음료,F,225,0,0,0,0,0,-225,2013,8,19,0
2013-08-19,lunch,burger&pizza,흑미버거,F,204,0,0,0,0,0,-204,2013,8,19,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2013-08-28,lunch,burger&pizza,까르보나라,F,248,0,0,0,0,0,-248,2013,8,28,2
2013-08-28,dinner,after school,신라면 set,F,148,0,0,0,0,0,-148,2013,8,28,2
2013-08-28,dinner,rice & soup 1,돈LA 갈비구이&영양부추,F,454,0,0,0,0,0,-454,2013,8,28,2
2013-08-28,lunch,rice & soup 1,A: 설렁탕&소면사리 812,F,550,0,0,0,0,0,-550,2013,8,28,2
2013-08-29,dinner,grill & fry,바베큐폭찹,F,300,0,0,0,0,0,-300,2013,8,29,3
2013-08-29,breakfast,take out,A: 샌드위치 콤보 510,F,88,0,0,0,0,0,-88,2013,8,29,3
2013-08-29,dinner,rice & soup 1,꽁치김치찌개,F,322,0,0,0,0,0,-322,2013,8,29,3
2013-08-29,lunch,burger&pizza,갈릭버거,F,224,0,0,0,0,0,-224,2013,8,29,3
2013-08-29,dinner,after school,어묵떡볶이 set,F,137,0,0,0,0,0,-137,2013,8,29,3
2013-08-29,lunch,take out,A: Meal box 590,F,232,0,0,0,0,0,-232,2013,8,29,3
2013-08-29,lunch,after school,라볶이 set,F,190,0,0,0,0,0,-190,2013,8,29,3
2013-08-29,lunch,grill & fry,팔락파니트,F,307,0,0,0,0,0,-307,2013,8,29,3
2013-08-29,dinner,noodle bar,매운해물쌀국수,F,214,0,0,0,0,0,-214,2013,8,29,3
2013-08-29,dinner,take out,A: 컵밥 450,F,283,0,0,0,0,0,-283,2013,8,29,3
2013-08-29,breakfast,rice & soup 1,콩나물국밥,F,58,0,0,0,0,0,-58,2013,8,29,3
2013-08-29,lunch,rice & soup 1,A: 설렁탕&소면사리 812,F,700,0,0,0,0,0,-700,2013,8,29,3
2013-08-29,lunch,noodle bar,물냉면or비빔냉면,F,217,0,0,0,0,0,-217,2013,8,29,3
2013-08-30,lunch,grill & fry,치킨티카마실라,F,313,0,0,0,0,0,-313,2013,8,30,4
2013-08-30,dinner,rice & soup 1,삼치엿장구이,F,303,0,0,0,0,0,-303,2013,8,30,4
2013-08-30,lunch,after school,해장라면 set,F,183,0,0,0,0,0,-183,2013,8,30,4
2013-08-30,dinner,after school,철판순대볶음set,F,173,0,0,0,0,0,-173,2013,8,30,4
2013-08-30,breakfast,take out,A: 샌드위치 콤보 510,F,82,0,0,0,0,0,-82,2013,8,30,4
2013-08-30,lunch,take out,A: Meal box 590,F,209,0,0,0,0,0,-209,2013,8,30,4
2013-08-30,dinner,noodle bar,치킨팟타이,F,226,0,0,0,0,0,-226,2013,8,30,4
2013-08-30,dinner,burger&pizza,고르곤졸라피자,F,194,0,0,0,0,0,-194,2013,8,30,4
2013-08-30,lunch,noodle bar,물냉면or비빔냉면,F,185,0,0,0,0,0,-185,2013,8,30,4
2013-08-30,dinner,take out,A: 컵밥 450,F,358,0,0,0,0,0,-358,2013,8,30,4
2013-08-30,breakfast,rice & soup 1,감자국,F,61,0,0,0,0,0,-61,2013,8,30,4
2013-08-30,lunch,rice & soup 1,A: 우거지순대국 750,F,596,0,0,0,0,0,-596,2013,8,30,4
2013-08-30,lunch,burger&pizza,새우필라프,F,209,0,0,0,0,0,-209,2013,8,30,4

In [32]:
식당['2015-01-13':'2015-03-03'][:10]

,dine_type,corner,menu,is_sold_out,use_count,pred_count,additional,good,ok,bad,diff_use_pred,year,month,day,wday
date,,,,,,,,,,,,,,,
2015-01-13,dinner,grill & fry,돈가스카레라이스,F,224,200,30,0,0,0,6,2015,1,13,1
2015-01-13,dinner,burger&pizza,불닭볶음밥&자몽샐러드,F,111,150,20,0,0,0,59,2015,1,13,1
2015-01-13,lunch,noodle bar,베트남양지쌀국수,F,233,250,40,0,0,0,57,2015,1,13,1
2015-01-13,lunch,take out,훈제오리&단호박샐러드,F,246,260,0,0,0,0,14,2015,1,13,1
2015-01-13,breakfast,take out,샌드위치콤보&음료&과일,F,36,38,20,0,0,0,22,2015,1,13,1
2015-01-13,lunch,after school,치즈라볶이&스팸김마리,F,154,140,20,0,0,0,6,2015,1,13,1
2015-01-13,dinner,noodle bar,기장조밥&닭가슴살채소볶음,F,80,80,10,0,0,0,10,2015,1,13,1
2015-01-13,dinner,take out,추억의도시락,F,113,80,10,0,0,0,-23,2015,1,13,1
2015-01-13,breakfast,rice & soup 1,순두부맑은국&돼지고기야채볶음,F,53,60,20,0,0,0,27,2015,1,13,1
2015-01-13,lunch,burger&pizza,치즈햄버거스테이크,F,161,200,30,0,0,0,69,2015,1,13,1

In [33]:
식당.truncate(after='2015')[-3:]

,dine_type,corner,menu,is_sold_out,use_count,pred_count,additional,good,ok,bad,diff_use_pred,year,month,day,wday
date,,,,,,,,,,,,,,,
2014-12-31,dinner,after school,얼큰김치라면&계란말이,F,2,80,30,0,0,0,108,2014,12,31,2
2014-12-31,breakfast,rice & soup 1,북어국&떡갈비엿장구이,F,38,30,20,0,0,0,12,2014,12,31,2
2014-12-31,dinner,rice & soup 1,설렁탕,F,28,220,60,0,0,0,252,2014,12,31,2

In [34]:
식당.truncate(before='2015')[:3]

,dine_type,corner,menu,is_sold_out,use_count,pred_count,additional,good,ok,bad,diff_use_pred,year,month,day,wday
date,,,,,,,,,,,,,,,
2015-01-02,dinner,after school,참깨라면&볶음김치김밥,F,39,80,10,0,0,0,51,2015,1,2,4
2015-01-02,lunch,after school,오징어김치볶음밥&계란후라이,F,158,170,40,0,0,0,52,2015,1,2,4
2015-01-02,breakfast,rice & soup 1,감자호박국&소고기야채볶음,F,35,20,10,0,0,0,-5,2015,1,2,4

# 맞춤형 날짜시간 범위

In [35]:
list(range(2013, 2020))

[2013, 2014, 2015, 2016, 2017, 2018, 2019]

In [36]:
dates = pd.date_range('2016-02-20', '2016-03-10')
dates

DatetimeIndex(['2016-02-20', '2016-02-21', '2016-02-22', '2016-02-23',
               '2016-02-24', '2016-02-25', '2016-02-26', '2016-02-27',
               '2016-02-28', '2016-02-29', '2016-03-01', '2016-03-02',
               '2016-03-03', '2016-03-04', '2016-03-05', '2016-03-06',
               '2016-03-07', '2016-03-08', '2016-03-09', '2016-03-10'],
              dtype='datetime64[ns]', freq='D')

In [37]:
ts = pd.Series(
    range(1,21), index=dates
)
ts

2016-02-20     1
2016-02-21     2
2016-02-22     3
2016-02-23     4
2016-02-24     5
2016-02-25     6
2016-02-26     7
2016-02-27     8
2016-02-28     9
2016-02-29    10
2016-03-01    11
2016-03-02    12
2016-03-03    13
2016-03-04    14
2016-03-05    15
2016-03-06    16
2016-03-07    17
2016-03-08    18
2016-03-09    19
2016-03-10    20
Freq: D, dtype: int32

In [38]:
ts['2016-02-25': '2016-03-05']

2016-02-25     6
2016-02-26     7
2016-02-27     8
2016-02-28     9
2016-02-29    10
2016-03-01    11
2016-03-02    12
2016-03-03    13
2016-03-04    14
2016-03-05    15
Freq: D, dtype: int32

특정 개수만큼 선택

In [39]:
pd.date_range('2016-12-16', periods=20)

DatetimeIndex(['2016-12-16', '2016-12-17', '2016-12-18', '2016-12-19',
               '2016-12-20', '2016-12-21', '2016-12-22', '2016-12-23',
               '2016-12-24', '2016-12-25', '2016-12-26', '2016-12-27',
               '2016-12-28', '2016-12-29', '2016-12-30', '2016-12-31',
               '2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04'],
              dtype='datetime64[ns]', freq='D')

In [40]:
pd.date_range(end='2016-12-16', periods=20)

DatetimeIndex(['2016-11-27', '2016-11-28', '2016-11-29', '2016-11-30',
               '2016-12-01', '2016-12-02', '2016-12-03', '2016-12-04',
               '2016-12-05', '2016-12-06', '2016-12-07', '2016-12-08',
               '2016-12-09', '2016-12-10', '2016-12-11', '2016-12-12',
               '2016-12-13', '2016-12-14', '2016-12-15', '2016-12-16'],
              dtype='datetime64[ns]', freq='D')

In [41]:
pd.date_range('2016-08-15 09:43:52', periods=10, normalize=True)

DatetimeIndex(['2016-08-15', '2016-08-16', '2016-08-17', '2016-08-18',
               '2016-08-19', '2016-08-20', '2016-08-21', '2016-08-22',
               '2016-08-23', '2016-08-24'],
              dtype='datetime64[ns]', freq='D')

In [42]:
pd.date_range('2016-01-01', '2017-01-01', freq='M')

DatetimeIndex(['2016-01-31', '2016-02-29', '2016-03-31', '2016-04-30',
               '2016-05-31', '2016-06-30', '2016-07-31', '2016-08-31',
               '2016-09-30', '2016-10-31', '2016-11-30', '2016-12-31'],
              dtype='datetime64[ns]', freq='M')

In [43]:
pd.date_range('2016-08-15 09:00', '2016-08-15 18:00', freq='1h30min')

DatetimeIndex(['2016-08-15 09:00:00', '2016-08-15 10:30:00',
               '2016-08-15 12:00:00', '2016-08-15 13:30:00',
               '2016-08-15 15:00:00', '2016-08-15 16:30:00',
               '2016-08-15 18:00:00'],
              dtype='datetime64[ns]', freq='90T')

In [45]:
날짜.iloc[-1]

'2015년 7월 27일'

In [46]:
불금 = pd.date_range('2013-08-06', '2015-07-27', freq='W-FRI')

In [47]:
불금

DatetimeIndex(['2013-08-09', '2013-08-16', '2013-08-23', '2013-08-30',
               '2013-09-06', '2013-09-13', '2013-09-20', '2013-09-27',
               '2013-10-04', '2013-10-11',
               ...
               '2015-05-22', '2015-05-29', '2015-06-05', '2015-06-12',
               '2015-06-19', '2015-06-26', '2015-07-03', '2015-07-10',
               '2015-07-17', '2015-07-24'],
              dtype='datetime64[ns]', length=103, freq='W-FRI')

In [48]:
식당.ix[불금][:5]

,dine_type,corner,menu,is_sold_out,use_count,pred_count,additional,good,ok,bad,diff_use_pred,year,month,day,wday
date,,,,,,,,,,,,,,,
2013-08-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-08-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-08-23,dinner,grill & fry,추억의도시락,F,211.0,0.0,0.0,0.0,0.0,0.0,-211.0,2013.0,8.0,23.0,4.0
2013-08-23,breakfast,rice & soup 1,참치김치찌개,F,43.0,0.0,0.0,0.0,0.0,0.0,-43.0,2013.0,8.0,23.0,4.0
2013-08-23,dinner,after school,라면+롤밥 &고급음료,F,149.0,0.0,0.0,0.0,0.0,0.0,-149.0,2013.0,8.0,23.0,4.0